package org.zjy.entity;

import java.util.Date;

public class Stu2major {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu2major.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu2major.studentId
     *
     * @mbg.generated
     */
    private Integer studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu2major.majorId
     *
     * @mbg.generated
     */
    private Integer majorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu2major.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu2major.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu2major.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu2major.id
     *
     * @return the value of stu2major.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu2major.id
     *
     * @param id the value for stu2major.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu2major.studentId
     *
     * @return the value of stu2major.studentId
     *
     * @mbg.generated
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu2major.studentId
     *
     * @param studentid the value for stu2major.studentId
     *
     * @mbg.generated
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu2major.majorId
     *
     * @return the value of stu2major.majorId
     *
     * @mbg.generated
     */
    public Integer getMajorid() {
        return majorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu2major.majorId
     *
     * @param majorid the value for stu2major.majorId
     *
     * @mbg.generated
     */
    public void setMajorid(Integer majorid) {
        this.majorid = majorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu2major.createtime
     *
     * @return the value of stu2major.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu2major.createtime
     *
     * @param createtime the value for stu2major.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu2major.updatetime
     *
     * @return the value of stu2major.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu2major.updatetime
     *
     * @param updatetime the value for stu2major.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu2major.deleted
     *
     * @return the value of stu2major.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu2major.deleted
     *
     * @param deleted the value for stu2major.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}